### ISSUE TITLE
Plans on upgrading this to 1.0?

### ISSUE THREAD

**Issue by kingflurkel** [sandro-k/mqtt-connection#1]
Hi!

Would love this component in a 1.0 polymer project. Any plans on updating?
Tried polyup, but got too many errors.

**Comment by sandro-k** [comment]
Hey checkout http://mqttjs.github.io/mqtt-elements/ . I have rewritten the mqtt wrapper to use polymer 1.0. I am going to add a info the the readme

**Comment by kingflurkel** [comment]
Very nice.
